import localFont from "next/font/local";
import AuthLayout from "@/Layouts/AuthLayout";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={` antialiased`}>
        <AuthLayout>{children}</AuthLayout>
      </body>
    </html>
  );
}