
import AdminLayout from "@/Layouts/AdminLayout";
import AdminProviders from "@/redux/AdminProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminRootLayout({ children }) {
    return (
        <html lang="en" className="" >
            <body className={` antialiased`} >
                <AdminProviders>
                    <AdminLayout>{children}</AdminLayout>
                </AdminProviders>
            </body>
        </html>
    );
}
