import localFont from "next/font/local";
import AuthLayout from "@/Layouts/AuthLayout";


export const metadata = {
  title: "Registration form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="" key={"auth-layout"}>
      <body body className={` antialiased`
      }>
        <AuthLayout>{children}</AuthLayout>
      </body >
    </html >
  );
}