
import CompanyLayout from "@/layouts/CompanyLayout";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminRootLayout({ children }) {
    return (
        <html lang="en" className="" >
            <body className={` antialiased`} >
                <CompanyLayout>{children}</CompanyLayout>
            </body>
        </html>
    );
}
