export const empInfoBaseTableData = [
    {
        id: "AB0001",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-f-f.png",
        email: "saleem@gmail.com",
        resident: "UAE",
        drivingLicense: "879343",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0002",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-f.jpg",
        email: "saleem@gmail.com",
        resident: "UAE",
        drivingLicense: "879343",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0003",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-m.jpg",
        email: "saleem@gmail.com",
        resident: "UAE",
        drivingLicense: "879343",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0004",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-m-m.png",
        email: "saleem@gmail.com",
        resident: "UAE",
        drivingLicense: "879343",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0005",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-f.jpg",
        email: "saleem@gmail.com",
        resident: "UAE",
        drivingLicense: "879343",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
]