
// export const columns = [
//     { field: "date", headerName: "DATE", align: "left" },
//     { field: "fullName", headerName: "FULL NAME", align: "left" },
//     { field: "residentCountry", headerName: "RESIDENT COUNTRY", align: "left" },
//     { field: "residentCity", headerName: "RESIDENT CITY", align: "left" },
//     { field: "drivingLicense", headerName: "DRIVING LICENSE", align: "left" },
//     { field: "phoneNumber", headerName: "PHONE NUMBER", align: "left" },
//     { field: "campaignName", headerName: "CAMPAIGN NAME", align: "left" },
//     { field: "remarks", headerName: "REMARKS", align: "left" },
//     {
//         field: "status",
//         headerName: "STATUS",
//         align: "left",
//         render: (row) => (
//             <Box
//                 sx={{
//                     backgroundColor: row.status === "Pending" ? "#D9F0FF" : "#FFE5E5",
//                     color: row.status === "Pending" ? "#007FFF" : "#FF0000",
//                     padding: "4px 8px",
//                     borderRadius: "4px",
//                 }}
//             >
//                 {row.status}
//             </Box>
//         ),
//     },
// ];

export const data = [
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "/images/profile-f.jpg",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Dubai",
        referBy: "John Smith",
       
       
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "/images/profile-f.jpg",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Sharjah",
        referBy: "John Smith",
      
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "/images/profile-f.jpg",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Dubai",
        referBy: "John Smith",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "/images/profile-m.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Abu Dhabi",
        referBy: "John Smith",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Dubai",
        referBy: "John Smith",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Sharjah",
        referBy: "John Smith",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Dubai",
        referBy: "John Smith",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Dubai",
        referBy: "John Smith",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Dubai",
        referBy: "John Smith",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
        drivingLicenseNo: "35444218797863",
        passportNo: "TA1822801",
        preferedWorkingCity: "Dubai",
        referBy: "John Smith",
    },

    // Add more rows for testing
];


// export const eventData = [
//     {
//         id: 1,
//         eventName: "Tech Conference 2024",
//         totalApplied: 120,
//         creationDate: "2023-11-01",
//         description: "A conference to explore the latest in tech.",
//         startDate: "2024-01-15",
//         endDate: "2024-01-18",
//         link: "https://example.com/tech-conference",
//         active: true,
//         bgColor: ["#FF5733", "#FFC300"],
//     },
//     {
//         id: 2,
//         eventName: "AI Workshop",
//         totalApplied: 80,
//         creationDate: "2023-09-20",
//         description: "Hands-on workshop on AI development.",
//         startDate: "2024-02-10",
//         endDate: "2024-02-12",
//         link: "https://example.com/ai-workshop",
//         active: true,
//         bgColor: ["#33FF57", "#33C7FF"],
//     },
//     {
//         id: 3,
//         eventName: "Startup Pitch Fest",
//         totalApplied: 50,
//         creationDate: "2023-10-10",
//         description: "A platform for startups to pitch their ideas.",
//         startDate: "2024-03-01",
//         endDate: "2024-03-03",
//         link: "https://example.com/pitch-fest",
//         active: false,
//         bgColor: ["#5733FF", "#C70039"],
//     },
//     {
//         id: 4,
//         eventName: "Marketing Summit",
//         totalApplied: 200,
//         creationDate: "2023-08-25",
//         description: "Discussing trends and strategies in marketing.",
//         startDate: "2024-04-10",
//         endDate: "2024-04-12",
//         link: "https://example.com/marketing-summit",
//         active: true,
//         bgColor: ["#FFC300", "#DAF7A6"],
//     },
//     {
//         id: 5,
//         eventName: "Healthcare Expo",
//         totalApplied: 300,
//         creationDate: "2023-06-30",
//         description: "An expo showcasing advancements in healthcare.",
//         startDate: "2024-05-20",
//         endDate: "2024-05-22",
//         link: "https://example.com/healthcare-expo",
//         active: true,
//         bgColor: ["#FF33C7", "#5733FF"],
//     },
//     {
//         id: 6,
//         eventName: "Blockchain Meetup",
//         totalApplied: 75,
//         creationDate: "2023-10-15",
//         description: "Networking event for blockchain enthusiasts.",
//         startDate: "2024-06-05",
//         endDate: "2024-06-06",
//         link: "https://example.com/blockchain-meetup",
//         active: false,
//         bgColor: ["#33FFF5", "#3375FF"],
//     },
//     {
//         id: 7,
//         eventName: "Design Conference",
//         totalApplied: 150,
//         creationDate: "2023-07-12",
//         description: "A conference focused on modern design trends.",
//         startDate: "2024-07-10",
//         endDate: "2024-07-12",
//         link: "https://example.com/design-conference",
//         active: true,
//         bgColor: ["#FF5733", "#FFC300"],
//     },
//     {
//         id: 8,
//         eventName: "Education Forum",
//         totalApplied: 90,
//         creationDate: "2023-09-05",
//         description: "A forum to discuss education advancements.",
//         startDate: "2024-08-01",
//         endDate: "2024-08-03",
//         link: "https://example.com/education-forum",
//         active: true,
//         bgColor: ["#33FF57", "#C70039"],
//     },
//     {
//         id: 9,
//         eventName: "Cybersecurity Summit",
//         totalApplied: 110,
//         creationDate: "2023-11-10",
//         description: "An event on tackling cybersecurity challenges.",
//         startDate: "2024-09-15",
//         endDate: "2024-09-17",
//         link: "https://example.com/cybersecurity-summit",
//         active: false,
//         bgColor: ["#FFC300", "#DAF7A6"],
//     },
//     {
//         id: 10,
//         eventName: "E-Commerce Expo",
//         totalApplied: 220,
//         creationDate: "2023-05-20",
//         description: "Exploring the world of e-commerce and retail.",
//         startDate: "2024-10-05",
//         endDate: "2024-10-07",
//         link: "https://example.com/ecommerce-expo",
//         active: true,
//         bgColor: ["#FF33C7", "#33FFF5"],
//     },
//     {
//         id: 11,
//         eventName: "Green Energy Conference",
//         totalApplied: 140,
//         creationDate: "2023-06-10",
//         description: "Showcasing sustainable energy solutions.",
//         startDate: "2024-11-20",
//         endDate: "2024-11-22",
//         link: "https://example.com/green-energy",
//         active: true,
//         bgColor: ["#33C7FF", "#5733FF"],
//     },
//     {
//         id: 12,
//         eventName: "Space Tech Forum",
//         totalApplied: 180,
//         creationDate: "2023-07-30",
//         description: "Discussing advancements in space exploration.",
//         startDate: "2024-12-01",
//         endDate: "2024-12-03",
//         link: "https://example.com/space-tech",
//         active: true,
//         bgColor: ["#C70039", "#DAF7A6"],
//     },
// ];


export const eventData = [
    {
        id: 1,
        eventName: "Tech Conference 2024",
        totalApplied: 120,
        creationDate: "2023-11-01",
        description: "Explore cutting-edge innovations in technology.",
        startDate: "2024-01-15",
        endDate: "2024-01-18",
        link: "https://example.com/tech-conference",
        active: true,
        bgColor: ["#4A90E2", "#50E3C2"], // Cool tech-inspired gradient
    },
    {
        id: 2,
        eventName: "AI & Machine Learning Summit",
        totalApplied: 95,
        creationDate: "2023-09-20",
        description: "Discover the latest advancements in AI and ML.",
        startDate: "2024-02-10",
        endDate: "2024-02-12",
        link: "https://example.com/ai-ml-summit",
        active: true,
        bgColor: ["#8E44AD", "#3498DB"], // Futuristic AI vibe
    },
    {
        id: 3,
        eventName: "Startup Pitch Fest",
        totalApplied: 50,
        creationDate: "2023-10-10",
        description: "Platform for startups to showcase their innovations.",
        startDate: "2024-03-01",
        endDate: "2024-03-03",
        link: "https://example.com/pitch-fest",
        active: false,
        bgColor: ["#16A085", "#2ECC71"], // Fresh entrepreneurial energy
    },
    {
        id: 4,
        eventName: "Marketing Summit",
        totalApplied: 200,
        creationDate: "2023-08-25",
        description: "Deep dive into the latest marketing strategies.",
        startDate: "2024-04-10",
        endDate: "2024-04-12",
        link: "https://example.com/marketing-summit",
        active: true,
        bgColor: ["#E74C3C", "#F1C40F"], // Bold, vibrant marketing colors
    },
    {
        id: 5,
        eventName: "Healthcare Innovations Expo",
        totalApplied: 310,
        creationDate: "2023-06-30",
        description: "Showcase of cutting-edge advancements in healthcare.",
        startDate: "2024-05-20",
        endDate: "2024-05-22",
        link: "https://example.com/healthcare-expo",
        active: true,
        bgColor: ["#27AE60", "#2980B9"], // Calming healthcare tones
    },
    {
        id: 6,
        eventName: "Blockchain Developers Meetup",
        totalApplied: 75,
        creationDate: "2023-10-15",
        description: "A networking event for blockchain enthusiasts.",
        startDate: "2024-06-05",
        endDate: "2024-06-06",
        link: "https://example.com/blockchain-meetup",
        active: false,
        bgColor: ["#2C3E50", "#8E44AD"], // Futuristic blockchain gradient
    },
    {
        id: 7,
        eventName: "Creative Design Conference",
        totalApplied: 150,
        creationDate: "2023-07-12",
        description: "Explore trends and techniques in modern design.",
        startDate: "2024-07-10",
        endDate: "2024-07-12",
        link: "https://example.com/design-conference",
        active: true,
        bgColor: ["#F39C12", "#E67E22"], // Creative, artistic tones
    },
    {
        id: 8,
        eventName: "Education Leaders Forum",
        totalApplied: 90,
        creationDate: "2023-09-05",
        description: "Discuss innovations shaping the future of education.",
        startDate: "2024-08-01",
        endDate: "2024-08-03",
        link: "https://example.com/education-forum",
        active: true,
        bgColor: ["#3498DB", "#1ABC9C"], // Bright, optimistic education colors
    },
    {
        id: 9,
        eventName: "Cybersecurity Challenges Summit",
        totalApplied: 110,
        creationDate: "2023-11-10",
        description: "Addressing modern cybersecurity challenges.",
        startDate: "2024-09-15",
        endDate: "2024-09-17",
        link: "https://example.com/cybersecurity-summit",
        active: false,
        bgColor: ["#34495E", "#2C3E50"], // Dark and secure tones
    },
    {
        id: 10,
        eventName: "E-Commerce Innovations Expo",
        totalApplied: 220,
        creationDate: "2023-05-20",
        description: "Explore innovations driving modern e-commerce.",
        startDate: "2024-10-05",
        endDate: "2024-10-07",
        link: "https://example.com/ecommerce-expo",
        active: true,
        bgColor: ["#1ABC9C", "#16A085"], // Fresh and vibrant retail colors
    },
    {
        id: 11,
        eventName: "Sustainable Energy Summit",
        totalApplied: 140,
        creationDate: "2023-06-10",
        description: "Highlighting sustainable energy solutions.",
        startDate: "2024-11-20",
        endDate: "2024-11-22",
        link: "https://example.com/green-energy",
        active: true,
        bgColor: ["#27AE60", "#2ECC71"], // Earthy green tones
    },
    {
        id: 12,
        eventName: "Space Exploration Forum",
        totalApplied: 180,
        creationDate: "2023-07-30",
        description: "Advancements in space technology and exploration.",
        startDate: "2024-12-01",
        endDate: "2024-12-03",
        link: "https://example.com/space-tech",
        active: true,
        bgColor: ["#8E44AD", "#2C3E50"], // Cosmic and futuristic tones
    },
];
