
// export const columns = [
//     { field: "date", headerName: "DATE", align: "left" },
//     { field: "fullName", headerName: "FULL NAME", align: "left" },
//     { field: "residentCountry", headerName: "RESIDENT COUNTRY", align: "left" },
//     { field: "residentCity", headerName: "RESIDENT CITY", align: "left" },
//     { field: "drivingLicense", headerName: "DRIVING LICENSE", align: "left" },
//     { field: "phoneNumber", headerName: "PHONE NUMBER", align: "left" },
//     { field: "campaignName", headerName: "CAMPAIGN NAME", align: "left" },
//     { field: "remarks", headerName: "REMARKS", align: "left" },
//     {
//         field: "status",
//         headerName: "STATUS",
//         align: "left",
//         render: (row) => (
//             <Box
//                 sx={{
//                     backgroundColor: row.status === "Pending" ? "#D9F0FF" : "#FFE5E5",
//                     color: row.status === "Pending" ? "#007FFF" : "#FF0000",
//                     padding: "4px 8px",
//                     borderRadius: "4px",
//                 }}
//             >
//                 {row.status}
//             </Box>
//         ),
//     },
// ];

export const data = [
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "/images/profile-f.jpg",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "/images/profile-f.jpg",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "/images/profile-f.jpg",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "/images/profile-m.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
    },
    {
        date: "12/09/2024",
        fullName: "Saleem Akhtar",
        email: "saleem@gmail.com",
        image: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
        residentCountry: "Pakistan",
        residentCity: "Karachi",
        drivingLicense: "Yes",
        phoneNumber: "+92 316 556 4650",
        campaignName: "Winter Fair",
        remarks: "--",
        status: "Pending",
        action: "View Details",
    },
    {
        date: "12/09/2024",
        fullName: "MD Kulem Ullah",
        email: "Kulem@gmail.com",
        image: "https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg",
        residentCountry: "India",
        residentCity: "Mumbai",
        drivingLicense: "No",
        phoneNumber: "+91 456 576 5460",
        campaignName: "Winter Fair",
        remarks: "Will be available after 2 days",
        status: "On Hold",
        action: "Edit",
    },

    // Add more rows for testing
];