import { DownloadIcon, PdfIcon } from "@/utils/Icons";

export const employeeData = [
  { key: "Employee ID", value: "AB00001" },
  { key: "Resident", value: "UAE" },
  { key: "Driving License", value: "879343" },
  { key: "Visa Type", value: "Own" },
  { key: "Passport Number", value: "TA1822801" },
  { key: "Phone Number", value: "+971 986556465" },
  { key: "WhatsApp Number", value: "+971 986556465" },
  { key: "Employee Type", value: "Rider" },
  { key: "Nationality", value: "UAE" },
  { key: "Marital Status", value: "Single" },
  { key: "Religion", value: "Islam" },
  { key: "Emergency Contact Name (UAE)", value: "Ramzan Ali" },
  { key: "Emergency Contact No. (UAE)", value: "+971 986556465" },
];

export const companyEmployeesTableData = [
  {
    id: "AB00001",
    name: "Saleem Ashfaq Muhammad Shehzad",
    image: "/images/profile-f-f.png",
    resident: "UAE",
    drivingLicense: "879343",
    passportNumber: "TA1822801",
    personalMobileNumber: "+971 986556465",
    rider_acquiring_vendor: "Rafiq Khan",
    vendor_image: "/images/vendor_image.png",
    rider_platform: "Careem",
    rider_platform_image: "/images/careem-logo.png",
    city: "Sharjah",
    visaStatus: "Own",
    contract: "--",
    salaryType: "Fixed",
    fixedSalaryAmount: 1200,
    actualJoiningDate: "12/06/24",
    gph_training: "Yes",
    c3_card: "Not Applied",
    c3_card_date: "12/05/22",
    status: "Pending",
    employeeType: "Rider",
    bike: "Assigned",
    sim: "Not Assigned",
    ghpTraining: 'Yes',
  },
  {
    id: "AB00002",
    name: "Mohsin Ullah Bin Suboor",
    image: "/images/profile-m-m.png",
    resident: "Non UAE",
    drivingLicense: "566699",
    passportNumber: "RT1234567",
    personalMobileNumber: "+971 345678910",
    rider_acquiring_vendor: "Rafiq Khan",
    vendor_image: "/images/vendor_image.png",
    rider_platform: "Careem",
    rider_platform_image: "/images/careem-logo.png",
    city: "Dubai",
    visaStatus: "Own",
    contract: "--",
    salaryType: "Commission",
    fixedSalaryAmount: 1500,
    actualJoiningDate: "12/06/24",
    gph_training: "Yes",
    c3_card: "Applied",
    c3_card_date: "12/05/22",
    status: "Approved",
    employeeType: "Rider",
    bike: "Not Assigned",
    sim: "Assigned",
    ghpTraining: 'No',

  },
  // Additional rows...
];

export const AssetHistoryTableData = [
  {
    bikePlateNumber: "1713",
    bikeCity: "Sharjah",
    bikeOwnershipImage: "/company/ABDS.svg",
    bikeOwnershipText: "ABDS",
    bikeIssueDate: "10/09/2024",
    bikeIssueTime: "10:00 AM",
    foodPermit: "Yes",
    mulkiya: "No",
    physicalAllocationImage: <PdfIcon />,
    physicalAllocationImage1: <DownloadIcon />,
    physicalAllocationText: "Allocation picture",
    clearanceDate: "--",
    vendorImage: "/images/vendor_image.png",
    riderAcquiringVendor: "Rafiq Khan",
    rider_platform_image: "/images/careem-logo.png",
    rider_platform: "Careem",
    status: "Currently Assigned",
  },
  {
    bikePlateNumber: "2134",
    bikeCity: "Dubai",
    bikeOwnershipImage: "/company/ABDS.svg",
    bikeOwnershipText: "ABDS",
    bikeIssueDate: "10/08/2024",
    bikeIssueTime: "11:00 AM",
    foodPermit: "Yes",
    mulkiya: "No",
    physicalAllocationImage: <PdfIcon />,
    physicalAllocationImage1: <DownloadIcon />,
    physicalAllocationText: "Allocation picture",
    clearanceDate: "12/09/2024",
    vendorImage: "/images/vendor_image.png",
    riderAcquiringVendor: "Abid Ali",
    rider_platform_image: "/images/careem-logo.png",
    rider_platform: "Careem",
    status: "Close",
  },
  // Additional rows...
];
