export const employeeData = [
    { key: "Employee ID", value: "AB00001" },
    { key: "Resident", value: "UAE" },
    { key: "Driving License", value: "879343" },
    { key: "Visa Type", value: "Own" },
    { key: "Passport Number", value: "TA1822801" },
    { key: "Phone Number", value: "+971 986556465" },
    { key: "WhatsApp Number", value: "+971 986556465" },
    { key: "Employee Type", value: "Rider" },
    { key: "Nationality", value: "UAE" },
    { key: "Marital Status", value: "Single" },
    { key: "Religion", value: "Islam" },
    { key: "Emergency Contact Name (UAE)", value: "Ramzan Ali" },
    { key: "Emergency Contact No. (UAE)", value: "+971 986556465" }
];

export const companyEmployeesTableData = [
    {
        id: "AB00001",
        name: "Saleem Ashfaq Muhammad Shehzad",
<<<<<<< Updated upstream
        image: "/images/profile-f-f.png",
=======
>>>>>>> Stashed changes
        resident: "UAE",
        drivingLicense: "879343",
        passportNumber: "TA1822801",
        personalMobileNumber: "+971 986556465",
<<<<<<< Updated upstream
        rider_acquiring_vendor: "Rafiq Khan",
        vendor_image: "/images/vendor_image.png",
        rider_platform: "Careem",
        rider_platform_image: "/images/careem-logo.png",
        city: "Sharjah",
        visaStatus: "Own",
        contract: "--",
        salaryType: "Fixed",
        fixedSalaryAmount: 1200,
        actualJoiningDate: "12/06/24",
        gph_training: "Yes",
        c3_card: "Not Applied",
        c3_card_date: "12/05/22",
        status: "Pending",
        employeeType: "Rider",
        bike: "Assigned",
        sim: "Not Assigned",
=======
        frontAssocation: "Careem",
        city: "Sharjah",
        visaStatus: "Own",
        salaryType: "Fixed",
        fixedSalaryAmount: 1200,
        actualJoiningDate: "12/06/24",
        dpSharing: "Yes",
        gtcApplied: "Not Applied",
        gtcAppliedDate: "12/05/22",
        status: "Pending",
        employeeType: "Rider",
        site: "Not Assigned",
>>>>>>> Stashed changes
    },
    {
        id: "AB00002",
        name: "Mohsin Ullah Bin Suboor",
<<<<<<< Updated upstream
        image: "/images/profile-m-m.png",
        resident: "Non UAE",
        drivingLicense: "566699",
        passportNumber: "RT1234567",
        personalMobileNumber: "+971 345678910",
        rider_acquiring_vendor: "Rafiq Khan",
        vendor_image: "/images/vendor_image.png",
        rider_platform: "Careem",
        rider_platform_image: "/images/careem-logo.png",
        city: "Dubai",
        visaStatus: "Own",
        contract: "--",
        salaryType: "Commission",
        fixedSalaryAmount: 1500,
        actualJoiningDate: "12/06/24",
        gph_training: "Yes",
        c3_card: "Applied",
        c3_card_date: "12/05/22",
        status: "Approved",
        employeeType: "Rider",
        bike: "Assigned",
        sim: "Not Assigned",
=======
        resident: "UAE",
        drivingLicense: "566699",
        passportNumber: "RT1234567",
        personalMobileNumber: "+971 345678910",
        frontAssocation: "Careem",
        city: "Dubai",
        visaStatus: "Own",
        salaryType: "Commission",
        fixedSalaryAmount: 1500,
        actualJoiningDate: "12/06/24",
        dpSharing: "Yes",
        gtcApplied: "Applied",
        gtcAppliedDate: "12/05/22",
        status: "Approved",
        employeeType: "Rider",
        site: "Assigned",
>>>>>>> Stashed changes
    },
    // Additional rows...
];